cosmosData = {
    "cosmos_data": {
        "TPL_PACKET": [
            ["PACKET_TIMESECONDS", 1743079567.230575, None],
            ["PACKET_TIMEFORMATTED", "2025/03/27 14:46:07.230", None],
            ["RECEIVED_TIMESECONDS", 1743079567.230575, None],
            ["RECEIVED_TIMEFORMATTED", "2025/03/27 14:46:07.230", None],
            ["RECEIVED_COUNT", 3331, None],
            ["CCSDS_VERSION", 0, None],
            ["CCSDS_TYPE", "TLM", None],
            ["CCSDS_SECONDARY_HEADER_FLAG", "TRUE", None],
            ["CCSDS_APID", "TPL", None],
            ["CCSDS_SEQUENCE_FLAG", "NOGROUP", None],
            ["CCSDS_SEQUENCE_COUNT", 1158, None],
            ["CCSDS_PACKET_DATA_LENGTH", 21, None],
            ["CCSDS_TIMESTAMP_PREAMBLE", 80, None],
            ["CCSDS_YEAR", 8192, None],
            ["CCSDS_MONTH", 4, None],
            ["CCSDS_DAY_OF_MONTH", 35, None],
            ["CCSDS_HOURS", 25, None],
            ["CCSDS_MINUTES", 66, None],
            ["CCSDS_SECONDS", 81, None],
            ["CCSDS_VERSION_NUMBER_MAJOR", 1, None],
            ["CCSDS_VERSION_NUMBER_MINOR", 1, None],
            ["CCSDS_VERSION_NUMBER_PATCH", 0, None],
            ["CCSDS_PACKET_ID", 0, None],
            ["TPL_RUN_MODE", "STANDBY", None],
            ["TPL_CURRENT_TEMPERATURE", 21.844323730468773, None],
            ["TPL_HEATER_SWITCH_STATUS", "OFF", None],
            ["TPL_TARGET_TEMPERATURE", 49.9999938964844, None],
        ],
        "PI_PAYLOAD_STATUS_PACKET": [
            ["PACKET_TIMESECONDS", 1743079567.980466, None],
            ["PACKET_TIMEFORMATTED", "2025/03/27 14:46:07.980", None],
            ["RECEIVED_TIMESECONDS", 1743079567.980466, None],
            ["RECEIVED_TIMEFORMATTED", "2025/03/27 14:46:07.980", None],
            ["RECEIVED_COUNT", 5265, None],
            ["CCSDS_VERSION", 0, None],
            ["CCSDS_TYPE", "TLM", None],
            ["CCSDS_SECONDARY_HEADER_FLAG", "TRUE", None],
            ["CCSDS_APID", 7, None],
            ["CCSDS_SEQUENCE_FLAG", "NOGROUP", None],
            ["CCSDS_SEQUENCE_COUNT", 1, None],
            ["CCSDS_PACKET_DATA_LENGTH", 22, None],
            ["CCSDS_TIMESTAMP_PREAMBLE", 0, None],
            ["CCSDS_YEAR", 8229, None],
            ["CCSDS_MONTH", 3, None],
            ["CCSDS_DAY_OF_MONTH", 39, None],
            ["CCSDS_HOURS", 20, None],
            ["CCSDS_MINUTES", 70, None],
            ["CCSDS_SECONDS", 7, None],
            ["CCSDS_VERSION_NUMBER_MAJOR", 1, None],
            ["CCSDS_VERSION_NUMBER_MINOR", 0, None],
            ["CCSDS_VERSION_NUMBER_PATCH", 0, None],
            ["CCSDS_PACKET_ID", 0, None],
            ["CAMUP", "ON", None],
            ["CPU_USEAGE", 1, None],
            ["RAM_USAGE", 91, None],
        ],
        "EPS_PACKET": [
            ["PACKET_TIMESECONDS", 1743079568.025397, None],
            ["PACKET_TIMEFORMATTED", "2025/03/27 14:46:08.025", None],
            ["RECEIVED_TIMESECONDS", 1743079568.025397, None],
            ["RECEIVED_TIMEFORMATTED", "2025/03/27 14:46:08.025", None],
            ["RECEIVED_COUNT", 5258, None],
            ["CCSDS_VERSION", 0, None],
            ["CCSDS_TYPE", "TLM", None],
            ["CCSDS_SECONDARY_HEADER_FLAG", "TRUE", None],
            ["CCSDS_APID", "EPS", None],
            ["CCSDS_SEQUENCE_FLAG", "NOGROUP", None],
            ["CCSDS_SEQUENCE_COUNT", 14852, None],
            ["CCSDS_PACKET_DATA_LENGTH", 66, None],
            ["CCSDS_TIMESTAMP_PREAMBLE", 80, None],
            ["CCSDS_YEAR", 8192, None],
            ["CCSDS_MONTH", 4, None],
            ["CCSDS_DAY_OF_MONTH", 35, None],
            ["CCSDS_HOURS", 25, None],
            ["CCSDS_MINUTES", 66, None],
            ["CCSDS_SECONDS", 40, None],
            ["CCSDS_VERSION_NUMBER_MAJOR", 2, None],
            ["CCSDS_VERSION_NUMBER_MINOR", 1, None],
            ["CCSDS_VERSION_NUMBER_PATCH", 1, None],
            ["CCSDS_PACKET_ID", 0, None],
            ["EPS_3V3_LINE_CURRENT", 216.855, None],
            ["EPS_3V3_LINE_VOLTAGE", 3.48432, None],
            ["EPS_5V_LINE_CURRENT", 168.055, None],
            ["EPS_5V_LINE_VOLTAGE", 4.9995400000000005, None],
            ["EPS_INPUT_LINE_CURRENT", 270.84, None],
            ["EPS_INPUT_LINE_VOLTAGE", 7.5335, None],
            ["EPS_SOLAR_PANEL_1_INPUT_CURRENT", 196.725, None],
            ["EPS_SOLAR_PANEL_1_OUTPUT_CURRENT", 2.745, None],
            ["EPS_SOLAR_PANEL_1_VOLTAGE", 0.07010999999999999, None],
            ["EPS_SOLAR_PANEL_2_INPUT_CURRENT", 191.23499999999999, None],
            ["EPS_SOLAR_PANEL_2_OUTPUT_CURRENT", 2.44, None],
            ["EPS_SOLAR_PANEL_2_VOLTAGE", 0.06669, None],
            ["EPS_3V3_LINE_SWITCH_STATE", "ON", None],
            ["EPS_5V_LINE_SWITCH_STATE", "ON", None],
            ["EPS_BATTERY_CURRENT", -195, None],
            ["EPS_BATTERY_TOTAL_VOLTAGE", 8.18, None],
            ["EPS_BATTERY_1_VOLTAGE", 4.245, None],
            ["EPS_BATTERY_2_VOLTAGE", 3.936, None],
            ["EPS_BATTERY_TEMPERATURE", 25.750000000000057, None],
            ["EPS_BATTERY_STATE_OF_CHARGE", 96, None],
            ["EPS_BATTERY_CONTROLLER_ERROR", "NO_ERROR", None],
            ["EPS_SOLAR_PANEL_1_TEMPERATURE", 22.8762, None],
            ["EPS_SOLAR_PANEL_1_THERMOMETER_ERROR", "NO_ERROR", None],
            ["EPS_SOLAR_PANEL_2_TEMPERATURE", 22.554, None],
            ["EPS_SOLAR_PANEL_2_THERMOMETER_ERROR", "NO_ERROR", None],
            ["EPS_MPPT_DRIVER_1_MODE", "MPPT", None],
            ["EPS_MPPT_DRIVER_1_DUTY_CYCLE", 194, None],
            ["EPS_MPPT_DRIVER_2_MODE", "MPPT", None],
            ["EPS_MPPT_DRIVER_2_DUTY_CYCLE", 197, None],
            ["EPS_DIRECT_ENERGY_TRANSFER_CURRENT", 0, None],
            ["EPS_DIRECT_ENERGY_TRANSFER_VOLTAGE", 0.0, None],
            ["EPS_DIRECT_ENERGY_TRANSFER_SHUNT_VOLTAGE", 0.0, None],
            ["EPS_DIRECT_ENERGY_TRANSFER_ERROR", "ERROR", None],
        ],
        "OBC_PACKET": [
            ["PACKET_TIMESECONDS", 1743079567.803089, None],
            ["PACKET_TIMEFORMATTED", "2025/03/27 14:46:07.803", None],
            ["RECEIVED_TIMESECONDS", 1743079567.803089, None],
            ["RECEIVED_TIMEFORMATTED", "2025/03/27 14:46:07.803", None],
            ["RECEIVED_COUNT", 5212, None],
            ["CCSDS_VERSION", 0, None],
            ["CCSDS_TYPE", "TLM", None],
            ["CCSDS_SECONDARY_HEADER_FLAG", "TRUE", None],
            ["CCSDS_APID", "OBC", None],
            ["CCSDS_SEQUENCE_FLAG", "NOGROUP", None],
            ["CCSDS_SEQUENCE_COUNT", 3014, None],
            ["CCSDS_PACKET_DATA_LENGTH", 15, None],
            ["CCSDS_TIMESTAMP_PREAMBLE", 80, None],
            ["CCSDS_YEAR", 8192, None],
            ["CCSDS_MONTH", 4, None],
            ["CCSDS_DAY_OF_MONTH", 35, None],
            ["CCSDS_HOURS", 25, None],
            ["CCSDS_MINUTES", 66, None],
            ["CCSDS_SECONDS", 81, None],
            ["CCSDS_VERSION_NUMBER_MAJOR", 4, None],
            ["CCSDS_VERSION_NUMBER_MINOR", 8, None],
            ["CCSDS_VERSION_NUMBER_PATCH", 0, None],
            ["CCSDS_PACKET_ID", 0, None],
            ["OBC_PROCESSOR_LOAD", 44, None],
            ["OBC_STORE_TELEMETRY", "OFF", None],
            ["OBC_TELEMETRY_STORAGE_ERROR", "OFF", None],
            ["OBC_CLOCK_ERROR", "OFF", None],
        ],
        "OBC_PROCESSOR_PACKET": [
            ["PACKET_TIMESECONDS", 1743079567.869935, None],
            ["PACKET_TIMEFORMATTED", "2025/03/27 14:46:07.869", None],
            ["RECEIVED_TIMESECONDS", 1743079567.869935, None],
            ["RECEIVED_TIMEFORMATTED", "2025/03/27 14:46:07.869", None],
            ["RECEIVED_COUNT", 5212, None],
            ["CCSDS_VERSION", 0, None],
            ["CCSDS_TYPE", "TLM", None],
            ["CCSDS_SECONDARY_HEADER_FLAG", "TRUE", None],
            ["CCSDS_APID", "OBC", None],
            ["CCSDS_SEQUENCE_FLAG", "NOGROUP", None],
            ["CCSDS_SEQUENCE_COUNT", 3015, None],
            ["CCSDS_PACKET_DATA_LENGTH", 31, None],
            ["CCSDS_TIMESTAMP_PREAMBLE", 80, None],
            ["CCSDS_YEAR", 8192, None],
            ["CCSDS_MONTH", 4, None],
            ["CCSDS_DAY_OF_MONTH", 35, None],
            ["CCSDS_HOURS", 25, None],
            ["CCSDS_MINUTES", 66, None],
            ["CCSDS_SECONDS", 81, None],
            ["CCSDS_VERSION_NUMBER_MAJOR", 4, None],
            ["CCSDS_VERSION_NUMBER_MINOR", 8, None],
            ["CCSDS_VERSION_NUMBER_PATCH", 0, None],
            ["CCSDS_PACKET_ID", 2, None],
            ["OBC_UPTIME", 1509198, None],
            ["OBC_PROCESSOR_TEMPERATURE", 27.043010711669922, None],
            ["OBC_PROCESSOR_VOLTAGE", 3.199023485183716, None],
            ["OBC_CURRENT_RAM_USAGE_PERCENTAGE", 60.41259765625, None],
            ["OBC_MAXIMUM_RAM_USAGE_PERCENTAGE", 65.3564453125, None],
        ],
    }
}

command = {"command": "ADCS       ON  ADCS_MAGNETORQUER_ENABLE ON"}

commandAndCosmos = cosmosData | command
